### ISSUE TITLE
/roll doesn't appear to work in private channels

### ISSUE THREAD

**Issue by Colbydude** [ErinMorelli/em-slack-roll#2]
Heya, tried installing this in my company's Slack chat, but /roll refuses to work within private channels. It will work with normal channels and private messages, though.

It returns the following 500 error when used in a private channel:

```
<DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Let me know if there's any additional information I can provide.

**Comment by ErinMorelli** [comment]
Hi @Colbydude - you need to invite the @roll_bot (EM Slack Roll) bot to join your private channel otherwise it can't post the roll results and you will receive that error. I've pushed out an update that will give more useful error messages in this case - let me know if for some reason that doesn't work for you. Thanks!

**Comment by Colbydude** [comment]
Ah, got it working! Thanks for the clarification!
